language: python
python:
#  - "2.5"  
  - "2.6"
  - "2.7"
#  - "3.3"

env:
  - DJANGO="django==1.6.1 --use-mirrors"
  - DJANGO="django==1.6 --use-mirrors"
  - DJANGO="django --use-mirrors" #should be latest stable
 # - DJANGO=https://github.com/django/django/archive/master.zip  

install:
 - sudo apt-get update
 - sudo apt-get install ruby
 - gem install sass
 - gem install compass
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage coveralls
 - pip install $DJANGO

before_script:
  - python manage.py compress

script:
 - coverage run --source=sew_django manage.py test

#matrix:
#  exclude:
#    - python: "3.3"
#      env: DJANGO="django==1.4.2 --use-mirrors"

after_success:
  - coverage report -m
  - coveralls

notifications:
  email:
    recipients:
      - jacek@ivolution.pl
