language: python
python:
#  - "2.5"  
  - "2.6"
  - "2.7"
  - "3.3"

env:
  - DJANGO="django==1.6.1 --use-mirrors"
  - DJANGO="django==1.6 --use-mirrors"
  - DJANGO=https://github.com/django/django/archive/master.zip  

install:
 - pip install -r requirements.txt --use-mirrors
 - pip install coverage coveralls
 - pip install $DJANGO

#script:
#  - coverage run --source=basic_cms setup.py test

#matrix:
#  exclude:
#    - python: "3.3"
#      env: DJANGO="django==1.4.2 --use-mirrors"

after_success:
#  - coverage report --omit="basic_cms/tests/*" -m
  - coveralls

notifications:
  email:
    recipients:
      - jacek@ivolution.pl
